# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.11
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: satishchoudhari13579@gmail.com
author_name: satishccy
preset_name: starter
project_name: votte-frontend

